{"status": "FAILURE", "result": {"exc_type": "UnpickleableExceptionWrapper", "exc_message": ["python_on_whales.exceptions", "DockerException", ["The command executed was `/usr/bin/docker compose --file docker-compose.yaml --file tunnels/iodine/docker-compose.yaml --env-file /tmp/tmpktodk9kz.env build`.\nIt returned with code 1\nThe content of stdout can be found above the stacktrace (it wasn't captured).\nThe content of stderr is 'open /home/ernesto/.docker/buildx/current: permission denied\n'\n"], "DockerException(\"The command executed was `/usr/bin/docker compose --file docker-compose.yaml --file tunnels/iodine/docker-compose.yaml --env-file /tmp/tmpktodk9kz.env build`.\\nIt returned with code 1\\nThe content of stdout can be found above the stacktrace (it wasn't captured).\\nThe content of stderr is 'open /home/ernesto/.docker/buildx/current: permission denied\\n'\\n\")"], "exc_module": "celery.utils.serialization"}, "traceback": "Traceback (most recent call last):\n  File \"/home/ernesto/Projects/DNSTunnelling-Benchmark-Docker/experiment/venv/lib/python3.12/site-packages/celery/app/trace.py\", line 453, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ernesto/Projects/DNSTunnelling-Benchmark-Docker/experiment/venv/lib/python3.12/site-packages/celery/app/trace.py\", line 736, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/ernesto/Projects/DNSTunnelling-Benchmark-Docker/experiment/tasks.py\", line 38, in run_experiment\n    docker_client.compose.build()\n  File \"/home/ernesto/Projects/DNSTunnelling-Benchmark-Docker/experiment/venv/lib/python3.12/site-packages/python_on_whales/components/compose/cli_wrapper.py\", line 108, in build\n    run(full_cmd, capture_stdout=False)\n  File \"/home/ernesto/Projects/DNSTunnelling-Benchmark-Docker/experiment/venv/lib/python3.12/site-packages/python_on_whales/utils.py\", line 230, in run\n    raise DockerException(\ncelery.utils.serialization.UnpickleableExceptionWrapper: DockerException(\"The command executed was `/usr/bin/docker compose --file docker-compose.yaml --file tunnels/iodine/docker-compose.yaml --env-file /tmp/tmpktodk9kz.env build`.\\nIt returned with code 1\\nThe content of stdout can be found above the stacktrace (it wasn't captured).\\nThe content of stderr is 'open /home/ernesto/.docker/buildx/current: permission denied\\n'\\n\")\n", "children": [], "date_done": "2024-09-26T10:23:39.101511+00:00", "task_id": "277150bd-c38f-452f-96c2-eb98300c513e"}